   #                                                  Titanic Exercise 

   ![titanic](https://userscontent2.emaze.com/images/a5f68f37-6349-4065-a1fc-921cbe7401b2/958230111417e36d6b3c67ffd7bc3494.jpeg)
   #### Practise Pandas

First of all, import the needed libraries.

In [18]:
import numpy as np
import pandas as pd

1. Read in filename and call the variable `titanic`
    - Explore the `titanic` dataset using `info`, `dtypes` & `describe`

In [112]:
titanic = pd.read_csv(r"C:\Users\data_\2026-02-BILBAO-FT-Data-Science\2-Data_Analysis\2-Pandas\Practica\7-Titanic\data\titanic.csv")
titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [20]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   str
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    str
 10  embarked   1307 non-null   str
 11  boat       486 non-null    str
 12  body       121 non-null    float64
 13  home.dest  745 non-null    str
dtypes: float64(3), int64(4), str(7)
memory usage: 143.3 KB

In [21]:
titanic.dtypes

pclass         int64
survived       int64
name             str
sex              str
age          float64
sibsp          int64
parch          int64
ticket           str
fare         float64
cabin            str
embarked         str
boat             str
body         float64
home.dest        str
dtype: object

In [22]:
titanic.describe().T

,count,mean,std,min,25%,50%,75%,max
pclass,1309.0,2.294882,0.837836,1.00,2.0000,3.0000,3.000,3.0000
survived,1309.0,0.381971,0.486055,0.00,0.0000,0.0000,1.000,1.0000
age,1046.0,29.881138,14.413493,0.17,21.0000,28.0000,39.000,80.0000
sibsp,1309.0,0.498854,1.041658,0.00,0.0000,0.0000,1.000,8.0000
parch,1309.0,0.385027,0.865560,0.00,0.0000,0.0000,0.000,9.0000
fare,1308.0,33.295479,51.758668,0.00,7.8958,14.4542,31.275,512.3292
body,121.0,160.809917,97.696922,1.00,72.0000,155.0000,256.000,328.0000

2. Create a separate dataframe with the columns `['name', 'sex', 'age']`, call it `people`

It can be done two ways, do it both!

In [23]:
people = pd.DataFrame(titanic, columns=["name", "sex", "age"])
people

                                                 name     sex    age
0                       Allen, Miss. Elisabeth Walton  female  29.00
1                      Allison, Master. Hudson Trevor    male   0.92
2                        Allison, Miss. Helen Loraine  female   2.00
3                Allison, Mr. Hudson Joshua Creighton    male  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
...                                               ...     ...    ...
1304                             Zabour, Miss. Hileni  female  14.50
1305                            Zabour, Miss. Thamine  female    NaN
1306                        Zakarian, Mr. Mapriededer    male  26.50
1307                              Zakarian, Mr. Ortin    male  27.00
1308                               Zimmerman, Mr. Leo    male  29.00

[1309 rows x 3 columns]

In [24]:
people = titanic[['name', 'sex', 'age']]
people

                                                 name     sex    age
0                       Allen, Miss. Elisabeth Walton  female  29.00
1                      Allison, Master. Hudson Trevor    male   0.92
2                        Allison, Miss. Helen Loraine  female   2.00
3                Allison, Mr. Hudson Joshua Creighton    male  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
...                                               ...     ...    ...
1304                             Zabour, Miss. Hileni  female  14.50
1305                            Zabour, Miss. Thamine  female    NaN
1306                        Zakarian, Mr. Mapriededer    male  26.50
1307                              Zakarian, Mr. Ortin    male  27.00
1308                               Zimmerman, Mr. Leo    male  29.00

[1309 rows x 3 columns]

3. Print the output of `people` showing the first three rows and the last four rows, using `append`,`tail` and `head`

In [25]:
people.head(3)

                             name     sex    age
0   Allen, Miss. Elisabeth Walton  female  29.00
1  Allison, Master. Hudson Trevor    male   0.92
2    Allison, Miss. Helen Loraine  female   2.00

In [26]:
people.tail(4)

                           name     sex   age
1305      Zabour, Miss. Thamine  female   NaN
1306  Zakarian, Mr. Mapriededer    male  26.5
1307        Zakarian, Mr. Ortin    male  27.0
1308         Zimmerman, Mr. Leo    male  29.0

In [ ]:
#vamos a asignar nombres a los 2 comandos anteriores para poder usar el comando "append":
first_three = people.head(3)
last_four = people.tail(4)
pd.concat([first_three, last_four]) #no sale porque según internet, el comando "append" sólo vale en pandas hasta la versión 2.0. 
#Ha sido sustituido por pd.concat

                                name     sex    age
0      Allen, Miss. Elisabeth Walton  female  29.00
1     Allison, Master. Hudson Trevor    male   0.92
2       Allison, Miss. Helen Loraine  female   2.00
1305           Zabour, Miss. Thamine  female    NaN
1306       Zakarian, Mr. Mapriededer    male  26.50
1307             Zakarian, Mr. Ortin    male  27.00
1308              Zimmerman, Mr. Leo    male  29.00

4. Slice the row from 3 to 9, call it `s_titanic`

In [33]:
s_titanic =  titanic.iloc[3:10] #con "iloc" hay que poner uno más que el índice hasta el que se quiere printear
s_titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"

5. Slice the row from 40 to 63 in reverse order, call it `s_titanic_rev`

In [ ]:
s_titanic_rev = titanic.iloc[63:39:-1] #en este caso se pone hasta el 39 porque va en orden inverso (1 menos que la posición deseada)
s_titanic_rev

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
63,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S,4,NaN,"Amenia, ND"
62,1,0,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,E31,S,NaN,NaN,"Amenia, ND"
61,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
60,1,0,"Cavendish, Mr. Tyrell William",male,36.0,1,0,19877,78.8500,C46,S,NaN,172.0,"Little Onn Hall, Staffs"
59,1,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0,0,17770,27.7208,NaN,C,5,NaN,"New York, NY"
58,1,0,"Case, Mr. Howard Brown",male,49.0,0,0,19924,26.0000,NaN,S,NaN,NaN,"Ascot, Berkshire / Rochester, NY"
57,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
56,1,1,"Carter, Mr. William Ernest",male,36.0,1,2,113760,120.0000,B96 B98,S,C,NaN,"Bryn Mawr, PA"
55,1,1,"Carter, Miss. Lucile Polk",female,14.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
54,1,1,"Carter, Master. William Thornton II",male,11.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
53,1,0,"Carrau, Mr. Jose Pedro",male,17.0,0,0,113059,47.1000,NaN,S,NaN,NaN,"Montevideo, Uruguay"
52,1,0,"Carrau, Mr. Francisco M",male,28.0,0,0,113059,47.1000,NaN,S,NaN,NaN,"Montevideo, Uruguay"
51,1,0,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,NaN,NaN,"New York, NY"
50,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.0,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Germantown, Philadelphia, PA"
49,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Austria-Hungary / Germantown, Philadelphia, PA"
48,1,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.0,0,0,PC 17606,27.4458,NaN,C,6,NaN,"Washington, DC"
47,1,1,"Calderhead, Mr. Edward Pennington",male,42.0,0,0,PC 17476,26.2875,E24,S,5,NaN,"New York, NY"
46,1,0,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,NaN,NaN,NaN
45,1,0,"Butt, Major. Archibald Willingham",male,45.0,0,0,113050,26.5500,B38,S,NaN,NaN,"Washington, DC"
44,1,1,"Burns, Miss. Elizabeth Margaret",female,41.0,0,0,16966,134.5000,E40,C,3,NaN,NaN
43,1,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.0,0,0,11813,76.2917,D15,C,8,NaN,"Philadelphia, PA"
42,1,1,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59.0,2,0,11769,51.4792,C101,S,D,NaN,"Belmont, MA"
41,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,0,0,PC 17610,27.7208,B4,C,6,NaN,"Denver, CO"
40,1,0,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C,NaN,NaN,"Philadelphia, PA"

6. Slice the columns from the starting column to `'parch'`, call it `left_columns`

In [ ]:
left_columns = titanic.loc[:, :'parch'] #loc es inclusivo por lo que metemos el nombre de la columna final
left_columns

,pclass,survived,name,sex,age,sibsp,parch
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2
...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0

7. Slice the columns from `'name'` to `'age'`, call it `middle_columns`

In [38]:
middle_columns = titanic.loc[:, 'name':'age']
middle_columns

                                                 name     sex    age
0                       Allen, Miss. Elisabeth Walton  female  29.00
1                      Allison, Master. Hudson Trevor    male   0.92
2                        Allison, Miss. Helen Loraine  female   2.00
3                Allison, Mr. Hudson Joshua Creighton    male  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
...                                               ...     ...    ...
1304                             Zabour, Miss. Hileni  female  14.50
1305                            Zabour, Miss. Thamine  female    NaN
1306                        Zakarian, Mr. Mapriededer    male  26.50
1307                              Zakarian, Mr. Ortin    male  27.00
1308                               Zimmerman, Mr. Leo    male  29.00

[1309 rows x 3 columns]

8. Slice the columns from `'ticket'` to the end, call it `right_columns`

In [39]:
right_columns = titanic.loc[:, 'ticket':]
right_columns

,ticket,fare,cabin,embarked,boat,body,home.dest
0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...
1304,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,315082,7.8750,NaN,S,NaN,NaN,NaN

9. What is the name of the oldest person who died in the Titanic? Was he or she travelling alone or had any family travelling with them?

In order to give an answer to the second question you should find out which columns give you that info. Usually part of your job as a Data Scientist will be get to know the dataset which you are working with. In this case the columns which give you that info are the following: 
        - 'sibsp' Number of Siblings/Spouses Aboard
        - 'parch' Number of Parents/Children Aboard

In [ ]:
#lo primero es identificar a la persona más vieja que murió. Para ello, necesitaremos las columnas "name", "age" y los "survived" que sean 0s
#lo más fácil es ir paso a paso, por lo que empezaremos por las personas que están muertas:
muertos = titanic['survived'] == 0 #esto es una condición booleana por lo que los resultados son True o False
#muertos (si sólo pones esto, te salen True y False para ver si están muertos o no). Por lo que es mejor:
titanic[muertos] #así sólo nos imprime los True de que survived = 0, es decir, los muertos:

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
2,1,0,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
7,1,0,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
9,1,0,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [70]:
#después, vamos a sacar cuál es la edad máxima:
edad_max = titanic['age'].max()
edad_max #esto es la edad máxima del total, pero lo que nos interesa es saber la edad máxima de los muertos (survived = 0)

np.float64(80.0)

In [73]:
titanic.loc[[titanic[muertos]["age"].idxmax()]] #doble corchete para que salga la info tipo dataframe
#la función "loc" localiza por índice. Por eso se pone idxmax en vez de max (max cuenta los valores NaN pero idxmax no)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1235,3,0,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.775,NaN,S,NaN,NaN,NaN

In [ ]:
#Para la segunda parte, la podemos responder con el output de la celda anterior:
# 'sibsp' Number of Siblings/Spouses Aboard = 0
# 'parch' Number of Parents/Children Aboard = 0
#Osea que murió sin familiares a bordo

10. Create the list of 5 random numbers of rows from 0 to the lenght of the dataframe, call it `rows`

ex. `rows = [3,7,99,52,48]` use `random` library

This list of numbers are random, could be different.

In [65]:
import random

In [ ]:
rows = random.sample(range(len(titanic)), 5) #crear una lista aleatoria con los títulos (índices) de las filas siendo 5 el número de filas
rows

[1130, 713, 630, 164, 791]

11. Create the list of three column labels, call it `cols`

In [93]:
cols = random.sample(list(titanic.columns), 3) #crear una lista aleatoria con los títulos de las columnas siendo 3 el número de columnas
cols

['survived', 'pclass', 'age']

12. Use both lists `rows` and `cols` to create a new dataframe

In [ ]:
pd.DataFrame.from_dict({'Columnas': cols, 'Filas': rows}, orient='index') #"from_dict" crea un diccionario a partir de los ejercicios anteriores
#Entonces, meteremos las listas "cols" y "rows" en el diccionario para poder crear un nuevo dataframe. Estas son los valores y les ponemos nombres a las claves
#rellena lo que no tiene valores con NaN
#"orient='index'" significa que las claves del diccionario se convertirán en los índices de las filas en lugar de las columnas

                 0       1    2      3      4
Columnas  survived  pclass  age    NaN    NaN
Filas         1130     713  630  164.0  791.0

13. Create a boolean array with the condition of being a woman or a man, using the `sex` column, where **female** is True. Call it `array_fe`

In [103]:
array_fe = (titanic['sex'] == 'female').values
array_fe

array([ True, False,  True, ..., False, False, False], shape=(1309,))

In [ ]:
titanic['sex'] == 'female' #otra manera

0        True
1       False
2        True
3       False
4        True
        ...
1304     True
1305     True
1306    False
1307    False
1308    False
Name: sex, Length: 1309, dtype: bool

14. Rename the column `"sex"` to `"gender"` and filter the `titanic` dataframe with the boolean array, call it `woman_titanic`

In [114]:
titanic.rename(columns={'sex': 'gender'}, inplace=True) #con "inplace = True" no dejará cambiar lo que acabas de reemplazar. Es decir, titanic ya se queda
#con la columna "gender"
titanic

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [122]:
woman_titanic = titanic[array_fe] #que te crea un dataframe que filtra sólo por las que sean mujeres (gender = female)
woman_titanic

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1286,3,1,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,C,NaN,NaN
1290,3,1,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,NaN,NaN,NaN
1300,3,1,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,NaN,NaN,NaN
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN

15. How many woman were younger than 18? Call the variable `minor_wo`

In [126]:
minor_wo = woman_titanic[woman_titanic['age'] < 18]
minor_wo

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
2,1,0,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
55,1,1,"Carter, Miss. Lucile Polk",female,14.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
92,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.0,1,0,17474,57.0000,B20,S,3,NaN,"Calgary, AB"
159,1,1,"Hippach, Miss. Jean Gertrude",female,16.0,0,1,111361,57.9792,B18,C,4,NaN,"Chicago, IL"
187,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S,9,NaN,"Paris, France"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1257,3,1,"Touma, Miss. Maria Youssef",female,9.0,1,1,2650,15.2458,NaN,C,C,NaN,NaN
1265,3,0,"Van Impe, Miss. Catharina",female,10.0,0,2,345773,24.1500,NaN,S,NaN,NaN,NaN
1279,3,0,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,NaN,NaN,NaN
1300,3,1,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,NaN,NaN,NaN
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN

16. How many woman that were less than 18 actually died? Call the variable `dead_wo`

In [127]:
dead_wo = minor_wo[minor_wo['survived'] == 0]
dead_wo

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
2,1,0,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
623,3,0,"Andersson, Miss. Ebba Iris Alfrida",female,6.0,4,2,347082,31.2750,NaN,S,NaN,NaN,"Sweden Winnipeg, MN"
624,3,0,"Andersson, Miss. Ellis Anna Maria",female,2.0,4,2,347082,31.2750,NaN,S,NaN,NaN,"Sweden Winnipeg, MN"
627,3,0,"Andersson, Miss. Ingeborg Constanzia",female,9.0,4,2,347082,31.2750,NaN,S,NaN,NaN,"Sweden Winnipeg, MN"
628,3,0,"Andersson, Miss. Sigrid Elisabeth",female,11.0,4,2,347082,31.2750,NaN,S,NaN,NaN,"Sweden Winnipeg, MN"
650,3,0,"Attalah, Miss. Malake",female,17.0,0,0,2627,14.4583,NaN,C,NaN,NaN,NaN
679,3,0,"Boulos, Miss. Nourelain",female,9.0,1,1,2678,15.2458,NaN,C,NaN,NaN,"Syria Kent, ON"
807,3,0,"Ford, Miss. Robina Maggie ""Ruby""",female,9.0,2,2,W./C. 6608,34.3750,NaN,S,NaN,NaN,"Rotherfield, Sussex, England Essex Co, MA"
828,3,0,"Goodwin, Miss. Jessie Allis",female,10.0,5,2,CA 2144,46.9000,NaN,S,NaN,NaN,"Wiltshire, England Niagara Falls, NY"
829,3,0,"Goodwin, Miss. Lillian Amy",female,16.0,5,2,CA 2144,46.9000,NaN,S,NaN,NaN,"Wiltshire, England Niagara Falls, NY"
841,3,0,"Hagardon, Miss. Kate",female,17.0,0,0,AQ/3. 30631,7.7333,NaN,Q,NaN,NaN,NaN
937,3,0,"Klasen, Miss. Gertrud Emilia",female,1.0,1,1,350405,12.1833,NaN,S,NaN,NaN,NaN
1098,3,0,"Palsson, Miss. Stina Viola",female,3.0,3,1,349909,21.0750,NaN,S,NaN,NaN,NaN
1099,3,0,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S,NaN,NaN,NaN
1112,3,0,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S,NaN,NaN,NaN
1156,3,0,"Rosblom, Miss. Salli Helena",female,2.0,1,1,370129,20.2125,NaN,S,NaN,NaN,NaN
1208,3,0,"Skoog, Miss. Mabel",female,9.0,3,2,347088,27.9000,NaN,S,NaN,NaN,NaN
1209,3,0,"Skoog, Miss. Margit Elizabeth",female,2.0,3,2,347088,27.9000,NaN,S,NaN,NaN,NaN
1230,3,0,"Strom, Miss. Telma Matilda",female,2.0,0,1,347054,10.4625,G6,S,NaN,NaN,NaN
1265,3,0,"Van Impe, Miss. Catharina",female,10.0,0,2,345773,24.1500,NaN,S,NaN,NaN,NaN
1279,3,0,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,NaN,NaN,NaN
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN

17. Drop rows with *Nan* in `titanic` with `how='any'` and print the shape

In [ ]:
ex_17 = titanic.dropna(how='any') #el comadno "dropna" elimina filas. how="any" elimina cada fila que tenga un NaN como mínimo 
ex_17

Empty DataFrame
Columns: [pclass, survived, name, gender, age, sibsp, parch, ticket, fare, cabin, embarked, boat, body, home.dest]
Index: []

In [ ]:
ex_17.shape #(filas, columnas)

(0, 14)

18. Drop rows with *Nan* in `titanic` with `how='all'` and print the shape

In [140]:
ex_18 = titanic.dropna(how='all') #how="all" elimina cada fila que tenga todos los valores de esa fila NaN
ex_18

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [141]:
ex_18.shape

(1309, 14)

Check in [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html) why the shapes are different.

19. Drop columns in `titanic` with more than 1000 missing values and print the columns remaining

In [143]:
titanic.dropna(axis=1, thresh=len(titanic) - 1000) #axis=1 se refiere a filas porque para eliminar columnas se tienen que tener en cuenta los valores de las filas
#len(titanic) es 1309 (Nº de filas)
#thresh = 1309 - 1000 = 309
#Las columnas deben tener al menos 309 valores válidos para quedarse. "Titanic" dataframe tenía 14 columnas, por lo que se han eliminado 2 columnas que tienen
#más de 1000 valores.

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,embarked,boat,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,S,2,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,S,11,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,S,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,S,NaN,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,S,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,C,NaN,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,C,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,C,NaN,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,C,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,S,NaN,NaN

20. Calculate the ratio of missing values at the `boat` column.

In [145]:
titanic['boat'].isnull().sum() / len(titanic) #la suma de los valores nulos de la columna "boat"/ la longitud de las filas de "titanic" dataframe

np.float64(0.6287242169595111)

21.  Group `titanic` by `'pclass'` and aggregate by the columns `age` & `fare`, by `max` and `median` and assign it to `by_class`

In [ ]:
#y hasta aquí da mi cerebro y tiempo

22. Print the maximum age in each class from `by_class`

23. Print the median fare in each class from `by_class`

24. Using [`.pivot_table()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html) to count how many women or men survived by class, call it `counted`.

Don't panic and read the documentation!

25. Add a new column with the sum of survived men and women, call it `counted['total']`

26. Sort `counted` by the `'total'` column. In which class the people survived the most?

27. Please, show only the rows using a mask with the following conditions: 
    - They are woman
    - From third class
    - Younger than 30
    - They survived
    
    ¿How many rows fulfill the condition?

28. Now, show only the rows using `.loc` with the following conditions: 
    - They are man
    - From first class
    - Older than 50
    - They died
    
    ¿How many rows fulfill the condition?

29. Print the uniques values at the column `'name'`

In [ ]:
titanic['name'].nunique()

1307

30. Find if was there any `name` repeated at the Titanic?

Hint: There were two people with the same name, who?

31. Using `matplotlib` find the appropriate visualization to show the distribution of the column `'age'`

In [ ]:
import matplotlib.pyplot as plt

32. Using `matplotlib` find the appropriate plot to visualize the column `'gender'`

32b. What if you also plot the column `'gender'` using the function [`countplot`](https://seaborn.pydata.org/generated/seaborn.countplot.html) from the library [`seaborn`](https://seaborn.pydata.org/)?

Remember you have never used `seaborn` before, therefore you should install it before importing it.

In [ ]:
import seaborn as sns

33. Using the function [`catplot`](https://seaborn.pydata.org/generated/seaborn.catplot.html) from the library `seaborn`, find out if the hypothesis _"Women are more likely to survive shipwrecks"_ is true or not.

You should get something like this:

![catplot](./img/catplotgen.png)

34. Using [`kdeplot`]("https://seaborn.pydata.org/generated/seaborn.kdeplot.html") from `seaborn` represent those who not survived distributed by age.<>

Hint: First you should "filter" the `titanic` dataset where the column "survived" is 0, indexing the column `"age"` only.

Arguments you should pass to the function: 

    - color = "red"
    - label = "Not Survived"
    - shade = True
    
You should get something like this:

![kdeplot](./img/kdeplotsur.png)