![imagen](https://cdn.foodbeast.com/content/wp-content/uploads/2012/03/beer-print-01-selectism.jpg)

# Ejercicio pandas estadística
Para este ejercicio se ha utilizado [un dataset de un concurso de kaggle](https://www.kaggle.com/nickhould/craft-cans), cuyo reto consiste en predecir el tipo de cerveza en función de sus características (nivel de alcohol, amargura, tamaño...).

# Ejercicio 1
Importa las librerias que consideres

In [1]:
import numpy as np
import pandas as pd

## Ejercicio 2
1. Importa el dataset "datasets_beer.csv"
2. Imprime por pantalla los primeros registros.
3. ¿Cuáles son sus columnas?
4. ¿Qué dimensiones tiene el DataFrame?

In [6]:
cerves = pd.read_csv(".\\data\datasets_beers.csv") #al no tener un link como en ejercicios anteriores sino un archivo, la importación funciona así (por lo que sea)
#es la ruta donde está el archivo
cerves

,Unnamed: 0,abv,ibu,id,name,style,brewery_id,ounces
0,0,0.050,NaN,1436,Pub Beer,American Pale Lager,408,12.0
1,1,0.066,NaN,2265,Devil's Cup,American Pale Ale (APA),177,12.0
2,2,0.071,NaN,2264,Rise of the Phoenix,American IPA,177,12.0
3,3,0.090,NaN,2263,Sinister,American Double / Imperial IPA,177,12.0
4,4,0.075,NaN,2262,Sex and Candy,American IPA,177,12.0
...,...,...,...,...,...,...,...,...
2405,2405,0.067,45.0,928,Belgorado,Belgian IPA,424,12.0
2406,2406,0.052,NaN,807,Rail Yard Ale,American Amber / Red Ale,424,12.0
2407,2407,0.055,NaN,620,B3K Black Lager,Schwarzbier,424,12.0
2408,2408,0.055,40.0,145,Silverback Pale Ale,American Pale Ale (APA),424,12.0
2409,2409,0.052,NaN,84,Rail Yard Ale (2009),American Amber / Red Ale,424,12.0

In [ ]:
cerves.head() #entiendo que por primeros registros se refiere a las 5 primeras filas. Para ello, el comando "head" por defecto

,Unnamed: 0,abv,ibu,id,name,style,brewery_id,ounces
0,0,0.050,NaN,1436,Pub Beer,American Pale Lager,408,12.0
1,1,0.066,NaN,2265,Devil's Cup,American Pale Ale (APA),177,12.0
2,2,0.071,NaN,2264,Rise of the Phoenix,American IPA,177,12.0
3,3,0.090,NaN,2263,Sinister,American Double / Imperial IPA,177,12.0
4,4,0.075,NaN,2262,Sex and Candy,American IPA,177,12.0

In [8]:
cerves.columns

Index(['Unnamed: 0', 'abv', 'ibu', 'id', 'name', 'style', 'brewery_id',
       'ounces'],
      dtype='str')

In [ ]:
cerves.info() #con este comando vemos toda la info del dataframe. Las dimensiones son 2410 filas y 8 colummnas

<class 'pandas.DataFrame'>
RangeIndex: 2410 entries, 0 to 2409
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2410 non-null   int64
 1   abv         2348 non-null   float64
 2   ibu         1405 non-null   float64
 3   id          2410 non-null   int64
 4   name        2410 non-null   str
 5   style       2405 non-null   str
 6   brewery_id  2410 non-null   int64
 7   ounces      2410 non-null   float64
dtypes: float64(3), int64(3), str(2)
memory usage: 150.8 KB

## Ejercicio 3
[Elimina la columna "Unnamed: 0"](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html)

In [ ]:
cerves.drop(columns=['Unnamed: 0']) # podríamos poner "inplace=True" en el comando si queremos que el dataframe se quede sin esa columna
#Seguro que la necesitamos en futuros ejercicios, así que la dejamos

,abv,ibu,id,name,style,brewery_id,ounces
0,0.050,NaN,1436,Pub Beer,American Pale Lager,408,12.0
1,0.066,NaN,2265,Devil's Cup,American Pale Ale (APA),177,12.0
2,0.071,NaN,2264,Rise of the Phoenix,American IPA,177,12.0
3,0.090,NaN,2263,Sinister,American Double / Imperial IPA,177,12.0
4,0.075,NaN,2262,Sex and Candy,American IPA,177,12.0
...,...,...,...,...,...,...,...
2405,0.067,45.0,928,Belgorado,Belgian IPA,424,12.0
2406,0.052,NaN,807,Rail Yard Ale,American Amber / Red Ale,424,12.0
2407,0.055,NaN,620,B3K Black Lager,Schwarzbier,424,12.0
2408,0.055,40.0,145,Silverback Pale Ale,American Pale Ale (APA),424,12.0
2409,0.052,NaN,84,Rail Yard Ale (2009),American Amber / Red Ale,424,12.0

In [11]:
cerves

,Unnamed: 0,abv,ibu,id,name,style,brewery_id,ounces
0,0,0.050,NaN,1436,Pub Beer,American Pale Lager,408,12.0
1,1,0.066,NaN,2265,Devil's Cup,American Pale Ale (APA),177,12.0
2,2,0.071,NaN,2264,Rise of the Phoenix,American IPA,177,12.0
3,3,0.090,NaN,2263,Sinister,American Double / Imperial IPA,177,12.0
4,4,0.075,NaN,2262,Sex and Candy,American IPA,177,12.0
...,...,...,...,...,...,...,...,...
2405,2405,0.067,45.0,928,Belgorado,Belgian IPA,424,12.0
2406,2406,0.052,NaN,807,Rail Yard Ale,American Amber / Red Ale,424,12.0
2407,2407,0.055,NaN,620,B3K Black Lager,Schwarzbier,424,12.0
2408,2408,0.055,40.0,145,Silverback Pale Ale,American Pale Ale (APA),424,12.0
2409,2409,0.052,NaN,84,Rail Yard Ale (2009),American Amber / Red Ale,424,12.0

## Ejercicio 4
¿Cuántas filas y columnas tiene el dataset?

In [12]:
#filas:
len(cerves)

2410

In [13]:
#filas:
cerves.shape[0]

2410

In [15]:
#columnas:
len(cerves.columns)

8

In [14]:
#columnas:
cerves.shape[1]

8

## Ejercicio 5
¿De qué tipo son los datos?

In [17]:
cerves.dtypes

Unnamed: 0      int64
abv           float64
ibu           float64
id              int64
name              str
style             str
brewery_id      int64
ounces        float64
dtype: object

## Ejercicio 6
Obtén en un nuevo DataFrame un resumen con las principales estadísticas de las columnas numéricas: mean, max, count, cuartiles...

In [18]:
cerves.describe()

,Unnamed: 0,abv,ibu,id,brewery_id,ounces
count,2410.000000,2348.000000,1405.000000,2410.000000,2410.000000,2410.000000
mean,1204.500000,0.059773,42.713167,1431.113278,231.749793,13.592241
std,695.851397,0.013542,25.954066,752.459975,157.685604,2.352204
min,0.000000,0.001000,4.000000,1.000000,0.000000,8.400000
25%,602.250000,0.050000,21.000000,808.250000,93.000000,12.000000
50%,1204.500000,0.056000,35.000000,1453.500000,205.000000,12.000000
75%,1806.750000,0.067000,64.000000,2075.750000,366.000000,16.000000
max,2409.000000,0.128000,138.000000,2692.000000,557.000000,32.000000

## Ejercicio 7
¿Cuántas birras hay de cada estilo en este dataset? [Investiga en la documentación de Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) si puedes hacer un conteo de valores.

In [22]:
#la acción "value_counts" cuenta cuántas veces sale el mismo valor. En este caso, para la columna "style"
cerves['style'].value_counts() #sale así (con ...) porque hay 99 estilos de cerveza diferentes y no se imprimen las 99 filas

style
American IPA                      424
American Pale Ale (APA)           245
American Amber / Red Ale          133
American Blonde Ale               108
American Double / Imperial IPA    105
                                 ...
American Malt Liquor                1
Grisette                            1
Flanders Oud Bruin                  1
Braggot                             1
Low Alcohol Beer                    1
Name: count, Length: 99, dtype: int64

## Ejercicio 8
1. Imprime por pantalla los registros desde el décimo hasta el vigésimo
2. De esos registros, imprime por pantalla desde la columna `name` a `ounces`, ambas incluidas
3. Quédate con las columnas `abv`, `ibu` y `ounces`, y además quédate sólo con los registros 10 al 20.
4. Convierte el resultado del apartado 3 en un array de `numpy`

In [26]:
cerves.iloc[10:21] #la primera posición es la 0, por eso para que se imprima el registro 20, hay que ponerlo hasta el 21

,Unnamed: 0,abv,ibu,id,name,style,brewery_id,ounces
10,10,0.072,NaN,2099,Sophomoric Saison,Saison / Farmhouse Ale,177,12.0
11,11,0.073,NaN,2098,Regional Ring Of Fire,Saison / Farmhouse Ale,177,12.0
12,12,0.069,NaN,2097,Garce Selé,Saison / Farmhouse Ale,177,12.0
13,13,0.085,NaN,1980,Troll Destroyer,Belgian IPA,177,12.0
14,14,0.061,60.0,1979,Bitter Bitch,American Pale Ale (APA),177,12.0
15,15,0.060,NaN,2318,Ginja Ninja,Cider,154,12.0
16,16,0.060,NaN,2170,Cherried Away,Cider,154,12.0
17,17,0.060,NaN,2169,Rhubarbarian,Cider,154,12.0
18,18,0.060,NaN,1502,BrightCider,Cider,154,12.0
19,19,0.082,NaN,1593,He Said Baltic-Style Porter,Baltic Porter,368,12.0
20,20,0.082,NaN,1592,He Said Belgian-Style Tripel,Tripel,368,12.0

In [27]:
cerves.loc[:, 'name':'ounces']

                      name                           style  brewery_id  ounces
0                 Pub Beer             American Pale Lager         408    12.0
1              Devil's Cup         American Pale Ale (APA)         177    12.0
2      Rise of the Phoenix                    American IPA         177    12.0
3                 Sinister  American Double / Imperial IPA         177    12.0
4            Sex and Candy                    American IPA         177    12.0
...                    ...                             ...         ...     ...
2405             Belgorado                     Belgian IPA         424    12.0
2406         Rail Yard Ale        American Amber / Red Ale         424    12.0
2407       B3K Black Lager                     Schwarzbier         424    12.0
2408   Silverback Pale Ale         American Pale Ale (APA)         424    12.0
2409  Rail Yard Ale (2009)        American Amber / Red Ale         424    12.0

[2410 rows x 4 columns]

In [28]:
cerves.loc[10:21, ['abv', 'ibu', 'ounces']]

      abv   ibu  ounces
10  0.072   NaN    12.0
11  0.073   NaN    12.0
12  0.069   NaN    12.0
13  0.085   NaN    12.0
14  0.061  60.0    12.0
15  0.060   NaN    12.0
16  0.060   NaN    12.0
17  0.060   NaN    12.0
18  0.060   NaN    12.0
19  0.082   NaN    12.0
20  0.082   NaN    12.0
21  0.099  92.0     8.4

In [ ]:
apartado_3 = cerves.loc[10:21, ['abv', 'ibu', 'ounces']]
apartado_3.to_numpy() #comando para pasar un dataframe a un array de numpy

array([[7.2e-02,     nan, 1.2e+01],
       [7.3e-02,     nan, 1.2e+01],
       [6.9e-02,     nan, 1.2e+01],
       [8.5e-02,     nan, 1.2e+01],
       [6.1e-02, 6.0e+01, 1.2e+01],
       [6.0e-02,     nan, 1.2e+01],
       [6.0e-02,     nan, 1.2e+01],
       [6.0e-02,     nan, 1.2e+01],
       [6.0e-02,     nan, 1.2e+01],
       [8.2e-02,     nan, 1.2e+01],
       [8.2e-02,     nan, 1.2e+01],
       [9.9e-02, 9.2e+01, 8.4e+00]])

## Ejercicio 9
¿Cuántas onzas pesan todas las birras del dataset?

In [31]:
cerves["ounces"].sum()

np.float64(32757.3)

## Ejercicio 10
El amargor de las cervezas se mide por su nivel de IBUs.
1. ¿Cuál es el amargor medio de las cervezas?
2. ¿El máximo? ¿Y el mínimo?
3. ¿Qué cerveza es la que tiene el amargor máximo? ¿Cuál es la de amargor mínimo?

In [37]:
cerves["ibu"].mean()

np.float64(42.71316725978647)

In [35]:
cerves["ibu"].max()

np.float64(138.0)

In [36]:
cerves["ibu"].min()

np.float64(4.0)

In [ ]:
cerves.loc[cerves['ibu'].idxmax(), 'name'] #identifica el máximo de la columna deseada (ibu) y devuelve el valor de la columna que necesitas (name)

'Bitter Bitch Imperial IPA'

In [39]:
cerves.loc[cerves['ibu'].idxmin(), 'name']

'Summer Solstice'

## Ejercicio 11
No queda muy claro cuánto de dispar, de dispersa, es la medida de IBU. Mediante estadística descriptiva (una o dos métricas, sin gráficas), razona la dispersión de la variable IBU.

In [ ]:
#del 11 al 15 es una fumada para mí en estos momentos, así que he decidido continuar

## Ejercicio 12
¿Existe alguna relación lineal entre las variables numéricas del dataset? Intenta pintar este razonamiento mediante un gráfico

## Ejercicio 13
Representa el nivel de alcohol (columna `abv`) en un histograma. ¿Se trata de una distribución simétrica o asimétrica?

## Ejercicio 14
Representa mediante un *boxplot* de `seaborn` la variable `abv`

## Ejercicio 15
1. ¿Qué estilos son los que tienen en media más alcohol?
2. ¿Y los estilos que son en media más amargos?

## Ejercicio 16
Carga el datasets de cervecerias `datasets_breweries.csv`

In [52]:
cervecerías = pd.read_csv(".\\data\datasets_breweries.csv")
cervecerías

     Unnamed: 0                           name           city state
0             0             NorthGate Brewing     Minneapolis    MN
1             1      Against the Grain Brewery     Louisville    KY
2             2       Jack's Abby Craft Lagers     Framingham    MA
3             3      Mike Hess Brewing Company      San Diego    CA
4             4        Fort Point Beer Company  San Francisco    CA
..          ...                            ...            ...   ...
553         553            Covington Brewhouse      Covington    LA
554         554                Dave's Brewfarm         Wilson    WI
555         555          Ukiah Brewing Company          Ukiah    CA
556         556        Butternuts Beer and Ale  Garrattsville    NY
557         557  Sleeping Lady Brewing Company      Anchorage    AK

[558 rows x 4 columns]

## Ejercicio 17
1. Renombra la columna `Unnamed: 0` como `brewery_id`
2. Renombra también la columna `name` por `brewery_name`. ¿Puedes hacer ambos apartados en una sola sentencia?

In [51]:
dataset_2 = cervecerías.rename(columns={'Unnamed: 0': 'brewery_id', 'name': 'brewery_name'})
dataset_2 #le asigno un nuevo nombre porque en los próximos ejercicios usaremos el dataset de cervecerías

     brewery_id                   brewery_name           city state
0             0             NorthGate Brewing     Minneapolis    MN
1             1      Against the Grain Brewery     Louisville    KY
2             2       Jack's Abby Craft Lagers     Framingham    MA
3             3      Mike Hess Brewing Company      San Diego    CA
4             4        Fort Point Beer Company  San Francisco    CA
..          ...                            ...            ...   ...
553         553            Covington Brewhouse      Covington    LA
554         554                Dave's Brewfarm         Wilson    WI
555         555          Ukiah Brewing Company          Ukiah    CA
556         556        Butternuts Beer and Ale  Garrattsville    NY
557         557  Sleeping Lady Brewing Company      Anchorage    AK

[558 rows x 4 columns]

## Ejercicio 18
Junta los dos datasets que tienes

In [ ]:
#ambos datasets (cerves y cervecerías) tienen columnas diferentes y dos iguales ("Unnamed: 0" y "name"). Lo que pasa es que se refieren a cosas diferentes: uno
#habla de ids y nombres de cerveza y el otro de cervecerías, por lo que usaremos el dataset del ejercicio anterior (dataset_2) con los nombres cambiados ya para que
# cada columna indique una cosa diferente y no haya cruzamiento de datos. Usamos el comando "merge"
new_dataset = pd.concat([cerves, dataset_2], axis=1) #"axis=1" me dice que vamos a concatenar los datasets por columnas, es decir, las columnas del segundo dataset se añaden
#después (a la derecha) del primer dataset
new_dataset

,Unnamed: 0,abv,ibu,id,name,style,brewery_id,ounces,brewery_id,brewery_name,city,state
0,0,0.050,NaN,1436,Pub Beer,American Pale Lager,408,12.0,0.0,NorthGate Brewing,Minneapolis,MN
1,1,0.066,NaN,2265,Devil's Cup,American Pale Ale (APA),177,12.0,1.0,Against the Grain Brewery,Louisville,KY
2,2,0.071,NaN,2264,Rise of the Phoenix,American IPA,177,12.0,2.0,Jack's Abby Craft Lagers,Framingham,MA
3,3,0.090,NaN,2263,Sinister,American Double / Imperial IPA,177,12.0,3.0,Mike Hess Brewing Company,San Diego,CA
4,4,0.075,NaN,2262,Sex and Candy,American IPA,177,12.0,4.0,Fort Point Beer Company,San Francisco,CA
...,...,...,...,...,...,...,...,...,...,...,...,...
2405,2405,0.067,45.0,928,Belgorado,Belgian IPA,424,12.0,NaN,NaN,NaN,NaN
2406,2406,0.052,NaN,807,Rail Yard Ale,American Amber / Red Ale,424,12.0,NaN,NaN,NaN,NaN
2407,2407,0.055,NaN,620,B3K Black Lager,Schwarzbier,424,12.0,NaN,NaN,NaN,NaN
2408,2408,0.055,40.0,145,Silverback Pale Ale,American Pale Ale (APA),424,12.0,NaN,NaN,NaN,NaN
2409,2409,0.052,NaN,84,Rail Yard Ale (2009),American Amber / Red Ale,424,12.0,NaN,NaN,NaN,NaN

In [ ]:
new_dataset.info() #comprobamos la info que tenemos en nuestro dataset. En teoría las casillas vacías se deberían haber rellenado con NaNs

<class 'pandas.DataFrame'>
RangeIndex: 2410 entries, 0 to 2409
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    2410 non-null   int64
 1   abv           2348 non-null   float64
 2   ibu           1405 non-null   float64
 3   id            2410 non-null   int64
 4   name          2410 non-null   str
 5   style         2405 non-null   str
 6   brewery_id    2410 non-null   int64
 7   ounces        2410 non-null   float64
 8   brewery_id    558 non-null    float64
 9   brewery_name  558 non-null    str
 10  city          558 non-null    str
 11  state         558 non-null    str
dtypes: float64(4), int64(3), str(5)
memory usage: 226.1 KB

## Ejercicio 19
1. ¿Cuántos estados diferentes hay?
2. ¿Y ciudades diferentes?
3. ¿Cuántas cervecerías hay?

## Ejercicio 20
Agrupa por estado y ciudad, la media, mediana y máximo nivel de alcohol

## Ejercicio 21
¿Cuáles son las cervezas más amargas que se consumen en Indiana, estado = `IN`?

## Ejercicio 22
Obtén una tabla con los principales estadísticos del campo `ibu`,  a nivel ciudad

## Ejercicio 23
Consigue en un DataFrame de todas las cervezas en cuyas cervecerías al menos haya una cerveza con un `abv` mínimo 0.07.

## Ejercicio 24
Teniendo en cuenta la media de amargor de todas las cervezas, obtén una tabla con las cervezas cuyos estados tengan una media de amargor en cerveza por encima de la media